# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: rateio-api

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  environment:
    # APP
    APP_NAME: rateio
    # JWT
    JWT_PRIVATE_KEY: ${file(./config/env.${self:custom.env}.yml):JWT_PRIVATE_KEY}
    JWT_EXPIRES_IN: ${file(./config/env.${self:custom.env}.yml):JWT_EXPIRES_IN}
    # MONGO
    DB_CONNECTION_STRING: ${file(./config/env.${self:custom.env}.yml):DB_CONNECTION_STRING}
    # social
    GOOGLE_AUTH_VALIDATE_URI: https://www.googleapis.com/oauth2/v3/tokeninfo

plugins:
  - serverless-offline

functions:
  ping:
    handler: handler.ping
    events:
      - http:
          path: ping
          method: get
          cors: true
  api:
    handler: router/api.routers
    events:
      - http:
          path: api/{proxy+}
          method: ANY
          cors: true

custom:
  env: dev
